name: sound_in_talk
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.0
  flutter_sound: ^7.7.0+1
  permission_handler: ^5.1.0+2
  get: ^3.26.0

  sip_ua: ^0.3.5
  flutter_webrtc: ^0.5.8
  socket_io_client: ^0.9.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true